📝translate : extraction.mdx 콘텐츠 번역
froggy1014/langchainjs-kr pull request #19
Opened 2024-07-02 09:10 UTC by bananana0118

# Check List

- [x] 한번 다시 읽어보기
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰어 피드백 반영

#17

2024-07-04 01:34 UTC, henrynoowah commented on docs/tutorials/extraction.mdx
> +먼저 우리가 텍스트에서 추출하고자 하는 정보가 무엇인지 정확히 설명해야 합니다.
@bananana0118 

**`describe`**
- 해당 섹션은 스키마 정의에 대한 내용으로 해당 문장에서 `describe`는 `설명`보다는 `스키마 정의` | `정의`라고 번역하는게 좋지 않을까요? 

```
alt 1: 먼저 우리가 텍스트에서 추출하고자 하는 정보에 대해 정확히 정의해야 합니다
alt 2: 먼저 우리가 텍스트에서 추출하고자 하는 정보를 정확히 설명하는 스키마를 정의해야 합니다
```

2024-07-04 01:47 UTC, henrynoowah commented on docs/tutorials/extraction.mdx
> +이 API와 사용할 수 있는 몇 가지 모델 목록[the
@bananana0118 
cc: @froggy1014 

참고 문서의 제목이 번역이 되어 페이지 섹션 딥링크가 정확이 작동하려면 주소도 업데이트 되어야 합니다

`../../docs/concepts#function-tool-calling` -> `../../docs/concepts#함수도구-호출--functiontool-calling-`


> 이 API와 사용할 수 있는 몇 가지 모델 목록은 [문서(함수/도구 호출 ( Function/Tool Calling ))](../../docs/concepts#함수도구-호출--functiontool-calling-)를 참조하세요

2024-07-19 18:50 UTC, froggy1014 requested changes
사소한 것만 수정해시면 바로 어프루브할게요 !

2024-07-19 18:50 UTC, froggy1014 commented on docs/tutorials/extraction.mdx
> +- [languagemodels](../../docs/concepts/#chat-models) 사용하기
language models 띄어쓰기를 해야할 것 같아요.

2024-07-19 18:50 UTC, froggy1014 commented on docs/tutorials/extraction.mdx
> +애플리케이션이 복잡하면 복잡해질수록, 애플리케이션의 체인이나 에이전트 안에서 무엇이 이루어지는지 검토하는 것은 중요합니다.
`무엇이 이루어지는지` 라는 표현보다는 `무슨 일이 일어나고 있는지` 라는 표현이 좀 더 자연스럽지않나라고 생각이 됩니다.

2024-07-19 18:50 UTC, froggy1014 commented on docs/tutorials/extraction.mdx
> +:::주의!
아래에서는 `중요`, 여기서는 `주의!` 라고 번역해주셨는데 하나로 통일하면 좋겠습니다.

저는 중요가 좋을 것 같아요

2024-07-22 14:20 UTC, froggy1014 approved these changes
LGTM

2024-07-22 14:21 UTC, merged